<a href="https://colab.research.google.com/github/paulagirones/Aerogels_thermal_conductivity/blob/main/aerogels_thermal_conductivity_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aerogels thermal conductivity

# DATA EXPLORATION

In [3]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('20250220_dataset.csv')

# Inspect the first rows
print("First 5 rows:")
display(df.head())

# Display information about the dataset
print("\nDataset information:")
df.info()

# Summary statistics for numerical variables
print("\nSummary statistics for numerical variables:")
display(df.describe())

First 5 rows:

,Entry,Drying,Purpose,Shape,First materials,Second materials,Modification,First material class,Second materials class,Modification class,...,BET surface area m2/g,BJH pore size nm,BJH pore volume (total) cm3/g,compression elastic modulus MPa,SEM,Thermal conductivity W/(m K),Thermal method,Thermal method detail,Unnamed: 28,Unnamed: 29
0,1,SCD,Not specific,Monolith?,Soda soap,NaN,NaN,Q,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16559 entries, 0 to 16558
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Entry                            16559 non-null  int64
 1   Drying                           16559 non-null  object
 2   Purpose                          16559 non-null  object
 3   Shape                            16559 non-null  object
 4   First materials                  16559 non-null  object
 5   Second materials                 6368 non-null   object
 6   Modification                     3086 non-null   object
 7   First material class             16559 non-null  object
 8   Second materials class           6368 non-null   object
 9   Modification class               3082 non-null   object
 10  Gelation class                   16559 non-null  object
 11  Solvent class                    16559 non-null  object
 12  Process                          16559 non-null  object
 13  Gelation mechanism               16559 non-null  object
 14  Final solvent                    16559 non-null  object
 15  Drying details                   16559 non-null  object
 16  Post drying treatment            3295 non-null   object
 17  Post-drying cross-linking        495 non-null    object
 18  Envelope density g/cm3           10755 non-null  float64
 19  Porosity                         7122 non-null   object
 20  BET surface area m2/g            7483 non-null   float64
 21  BJH pore size nm                 1012 non-null   float64
 22  BJH pore volume (total) cm3/g    2479 non-null   float64
 23  compression elastic modulus MPa  3001 non-null   float64
 24  SEM                              15605 non-null  object
 25  Thermal conductivity W/(m K)     2484 non-null   float64
 26  Thermal method                   2493 non-null   object
 27  Thermal method detail            2490 non-null   object
 28  Unnamed: 28                      0 non-null      float64
 29  Unnamed: 29                      29 non-null     object
dtypes: float64(7), int64(1), object(22)
memory usage: 3.8+ MB

Summary statistics for numerical variables:

,Entry,Envelope density g/cm3,BET surface area m2/g,BJH pore size nm,BJH pore volume (total) cm3/g,compression elastic modulus MPa,Thermal conductivity W/(m K),Unnamed: 28
count,16559.000000,10755.000000,7483.000000,1012.000000,2479.000000,3001.000000,2484.000000,0.0
mean,8280.000000,0.153072,256.800703,47.061556,1.373567,44.144848,0.050934,NaN
std,4780.315889,0.195817,344.626890,421.069389,2.023918,598.211022,0.152535,NaN
min,1.000000,0.000200,0.000000,0.050000,0.000160,0.000050,0.010000,NaN
25%,4140.500000,0.029250,60.000000,11.137500,0.310000,0.160000,0.028522,NaN
50%,8280.000000,0.084000,200.000000,16.300000,0.790000,1.700000,0.036550,NaN
75%,12419.500000,0.196700,366.000000,23.727500,1.530000,14.000000,0.048000,NaN
max,16559.000000,2.514200,17351.000000,7413.000000,24.210000,25160.000000,7.000000,NaN

# CLEANING AND PRE-PROCESSING

In [4]:
# Check missing values
print("Missing values:")
display(df.isna().sum())

print("Percentage of missing values:")
display((df.isna().sum() / len(df)) * 100)

# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")

Missing values:

Entry                                  0
Drying                                 0
Purpose                                0
Shape                                  0
First materials                        0
Second materials                   10191
Modification                       13473
First material class                   0
Second materials class             10191
Modification class                 13477
Gelation class                         0
Solvent class                          0
Process                                0
Gelation mechanism                     0
Final solvent                          0
Drying details                         0
Post drying treatment              13264
Post-drying cross-linking          16064
Envelope density g/cm3              5804
Porosity                            9437
BET surface area m2/g               9076
BJH pore size nm                   15547
BJH pore volume (total) cm3/g      14080
compression elastic modulus MPa    13558
SEM                                  954
Thermal conductivity W/(m K)       14075
Thermal method                     14066
Thermal method detail              14069
Unnamed: 28                        16559
Unnamed: 29                        16530
dtype: int64

Percentage of missing values:

Entry                                0.000000
Drying                               0.000000
Purpose                              0.000000
Shape                                0.000000
First materials                      0.000000
Second materials                    61.543571
Modification                        81.363609
First material class                 0.000000
Second materials class              61.543571
Modification class                  81.387765
Gelation class                       0.000000
Solvent class                        0.000000
Process                              0.000000
Gelation mechanism                   0.000000
Final solvent                        0.000000
Drying details                       0.000000
Post drying treatment               80.101455
Post-drying cross-linking           97.010689
Envelope density g/cm3              35.050426
Porosity                            56.990156
BET surface area m2/g               54.810073
BJH pore size nm                    93.888520
BJH pore volume (total) cm3/g       85.029289
compression elastic modulus MPa     81.876925
SEM                                  5.761217
Thermal conductivity W/(m K)        84.999094
Thermal method                      84.944743
Thermal method detail               84.962860
Unnamed: 28                        100.000000
Unnamed: 29                         99.824869
dtype: float64

Duplicate rows: 0

In [6]:
#Rename columns
df = df.rename(columns={
    'Thermal conductivity W/(m K)': 'Thermal_conductivity',
    'Envelope density g/cm3': 'Density',
    'BET surface area m2/g': 'BET',
    'BJH pore size nm': 'Pore_size',
    'BJH pore volume (total) cm3/g': 'Pore_volume',
    'compression elastic modulus MPa': 'Elastic_modulus'
})

df.head()

,Entry,Drying,Purpose,Shape,First materials,Second materials,Modification,First material class,Second materials class,Modification class,...,BET,Pore_size,Pore_volume,Elastic_modulus,SEM,Thermal_conductivity,Thermal method,Thermal method detail,Unnamed: 28,Unnamed: 29
0,1,SCD,Not specific,Monolith?,Soda soap,NaN,NaN,Q,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#